# Generated by Django 3.1.3 on 2020-12-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20201201_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('email_sent', models.CharField(default='no', max_length=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
