# Generated by Django 3.1.3 on 2020-12-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_sent',
        ),
    ]
