# Generated by Django 3.1.3 on 2020-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_contact_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_sent',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
